### ISSUE TITLE
Divisão equilibrada das atividades do grupo

### ISSUE THREAD

**Issue by vivianesanguinett** [OtacilioN/discreta03g02#5]
É interessante que consigamos dividir ,de forma mais equilibrada possível, as implementações no nosso  código,de maneira que todos contribuam significativamente. Gostaria de sugestões de como seria a melhor forma de fazermos isso.

**Comment by OtacilioN** [comment]
Oks, realmente tô dando uma vacilada nesse quesito =/ Gogo team! Acho que vou só terminar a funcao de recebimento de dados hj, que tá quase pronta e dar uma esperada.

**Comment by OtacilioN** [comment]
Só adiantando também que dei uma corrida na minha parte pelo fato de que Sexta, Sábado e Domingo vou estar sendo Juiz da OBR, então simplesmente não vou conseguir fazer nada...

**Comment by vivianesanguinett** [comment]
Ok

**Comment by felipecalado** [comment]
Grupo, peço perdão pela ausência nesses últimos dias, mas fiquei sem internet até agora a pouco. Aparentemente o problema foi resolvido. Hoje vou estudar o código e tentar trabalhar nele logo mais.

**Comment by vivianesanguinett** [comment]
certo
