### ISSUE TITLE
Redes de PETRI pra teste. 

### ISSUE THREAD

**Issue by OtacilioN** [OtacilioN/discreta03g02#8]
Se alguém puder ir pensando em redes de PETRI com vários aspectos diferentes pra debugar o código postar aqui: Uma foto da rede de Petri desenhada, e faz o arquivo que descreve essa rede de Petri que vai alimentar a entrada do programa.

**Comment by vivianesanguinett** [comment]
Adicionei o que foi feito em sala pelo professor ,ao menos por enquanto. Qualquer coisa,fazemos outra.
